// kiro의 포트폴리오 데이터
export const kiroContent = {
  name: 'Kiro',
  siteName: 'Kiro Portfolio',
  portfolios: [
    {
      id: 1,
      title: '북서울 미술관\n기획전 일렉트릭 쇼크',
      workName: 'Ossia Organ',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 1',
      category: '전시',
      layoutType: 'photo',
      imageDescription: '전시 전경 이미지',
    },
    {
      id: 2,
      title: '아트센터 예술의시간\n조민선 작가 개인전',
      workName: 'Quintuple Odyssey',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 2',
      category: '전시',
      layoutType: 'photo',
      imageDescription: '전시 작품 이미지',
    },
    {
      id: 3,
      title: '당산 생각의 벙커\n공동전시',
      workName: 'CO-AUDIENCE',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 3',
      category: '전시',
      layoutType: 'photo',
      imageDescription: '전시 공간 이미지',
    },
    {
      id: 4,
      title: '갤러리 잔느\nD.cus 팀 전시',
      workName: 'Warm Window',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 4',
      category: '전시',
      layoutType: 'photo',
      imageDescription: '갤러리 전시 이미지',
    },
    {
      id: 5,
      title: '인터랙티브 미디어 아트\n기초 강의',
      workName: 'Interactive Media Basics',
      image: '/images/kiro/portfolio1.png',
      description: '인터랙티브 미디어 아트의 기초 개념과 실습을 다루는 강의입니다. 참가자들은 다양한 미디어 도구를 사용하여 창의적인 작품을 만들어봅니다.',
      category: '강의',
      layoutType: 'text',
      leftColumnText: '이 강의에서는 인터랙티브 미디어 아트의 역사와 주요 작가들, 그리고 기본적인 기술적 개념들을 배웁니다. Processing, p5.js 등의 도구를 활용합니다.',
      rightColumnText: '실습 위주의 커리큘럼으로, 참가자들은 직접 인터랙티브 작품을 기획하고 제작하는 경험을 합니다. 최종 작품은 전시회를 통해 발표됩니다.',
    },
    {
      id: 6,
      title: '크리에이티브 코딩\n워크샵',
      workName: 'Creative Coding Workshop',
      image: '/images/kiro/portfolio2.webp',
      description: '코딩을 활용한 창의적 표현 방법을 배우는 워크샵입니다.',
      category: '강의',
      layoutType: 'text',
      leftColumnText: '프로그래밍의 기초부터 시작하여 예술적 표현을 위한 코딩 기법을 학습합니다.',
      rightColumnText: '다양한 비주얼 아트 작품을 코드로 구현해보며 창의성과 기술을 동시에 발전시킵니다.',
    },
    {
      id: 7,
      title: '디지털 아트\n마스터클래스',
      workName: 'Digital Art Masterclass',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 7',
      category: '강의',
      layoutType: 'text',
    },
    {
      id: 8,
      title: '3D 인터랙션\n게임 프로젝트',
      workName: '3D Interaction Game',
      image: '/images/kiro/portfolio4.jpg',
      description: 'Unity를 활용한 3D 인터랙션 게임 프로젝트입니다. 플레이어의 움직임에 반응하는 몰입감 있는 경험을 제공합니다.',
      category: 'Unity',
      layoutType: 'photo',
      imageDescription: '게임 스크린샷',
    },
    {
      id: 9,
      title: '가상 현실\n체험 프로젝트',
      workName: 'VR Experience',
      image: '/images/kiro/portfolio1.png',
      description: 'VR 기술을 활용한 몰입형 체험 콘텐츠입니다.',
      category: 'Unity',
      layoutType: 'photo',
      imageDescription: 'VR 체험 장면',
    },
    {
      id: 10,
      title: '인터랙티브 설치\n아트 Unity',
      workName: 'Interactive Installation',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 10',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 11,
      title: 'Unity 기반\n미디어 아트',
      workName: 'Media Art Unity',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 11',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 12,
      title: '아두이노 센서\n인터랙션',
      workName: 'Arduino Sensor Interaction',
      image: '/images/kiro/portfolio4.jpg',
      description: '다양한 센서를 활용한 인터랙티브 아트 프로젝트입니다. 관람객의 움직임과 환경 변화에 반응하는 작품을 만들었습니다.',
      category: 'Arduino',
      layoutType: 'text',
      leftColumnText: '초음파 센서, 온도 센서, 조도 센서 등을 활용하여 환경 데이터를 수집합니다.',
      rightColumnText: '수집된 데이터는 실시간으로 시각화되어 관람객에게 새로운 경험을 제공합니다.',
    },
    {
      id: 13,
      title: '로봇 아트\n프로젝트',
      workName: 'Robot Art Project',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 13',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 14,
      title: '인터랙티브 조명\n설치 작품',
      workName: 'Interactive Light Installation',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 14',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 15,
      title: '물리적 컴퓨팅\n아트워크',
      workName: 'Physical Computing Artwork',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 15',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 16,
      title: '추가 전시\n프로젝트 1',
      workName: 'Additional Exhibition 1',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 16',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 17,
      title: '추가 전시\n프로젝트 2',
      workName: 'Additional Exhibition 2',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 17',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 18,
      title: '국립현대미술관\n디지털 아트 전시',
      workName: 'Digital Art Exhibition',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 18',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 19,
      title: '서울시립미술관\n미디어 아트 쇼',
      workName: 'Media Art Show',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 19',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 20,
      title: '갤러리 현대\n그룹전',
      workName: 'Group Exhibition',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 20',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 21,
      title: '아트센터 나비\n개인전',
      workName: 'Solo Exhibition',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 21',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 22,
      title: '문화역서울284\n기획전',
      workName: 'Curated Exhibition',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 22',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 23,
      title: '추가 전시\n프로젝트 3',
      workName: 'Additional Exhibition 3',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 23',
      category: '전시',
      layoutType: 'photo',
    },
    {
      id: 24,
      title: '프로그래밍 기초\n온라인 강의',
      workName: 'Programming Basics Online',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 24',
      category: '강의',
      layoutType: 'text',
    },
    {
      id: 25,
      title: '인터랙티브 디자인\n실습 강의',
      workName: 'Interactive Design Practice',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 25',
      category: '강의',
      layoutType: 'text',
    },
    {
      id: 26,
      title: '미디어 아트\n이론과 실기',
      workName: 'Media Art Theory & Practice',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 26',
      category: '강의',
      layoutType: 'text',
    },
    {
      id: 27,
      title: 'Unity 게임 개발\n심화 과정',
      workName: 'Unity Game Development Advanced',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 27',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 28,
      title: 'VR/AR 개발\n프로젝트',
      workName: 'VR/AR Development Project',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 28',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 29,
      title: 'Unity 셰이더\n프로그래밍',
      workName: 'Unity Shader Programming',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 29',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 30,
      title: '인터랙티브 미디어\nUnity 프로젝트',
      workName: 'Interactive Media Unity',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 30',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 31,
      title: 'Unity 아트\n인스톨레이션',
      workName: 'Unity Art Installation',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 31',
      category: 'Unity',
      layoutType: 'photo',
    },
    {
      id: 32,
      title: '아두이노 IoT\n프로젝트',
      workName: 'Arduino IoT Project',
      image: '/images/kiro/portfolio4.jpg',
      description: '포트폴리오 설명 32',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 33,
      title: '센서 기반\n인터랙티브 아트',
      workName: 'Sensor-based Interactive Art',
      image: '/images/kiro/portfolio1.png',
      description: '포트폴리오 설명 33',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 34,
      title: '아두이노 모터\n제어 프로젝트',
      workName: 'Arduino Motor Control',
      image: '/images/kiro/portfolio2.webp',
      description: '포트폴리오 설명 34',
      category: 'Arduino',
      layoutType: 'text',
    },
    {
      id: 35,
      title: '물리적 인터랙션\n디자인',
      workName: 'Physical Interaction Design',
      image: '/images/kiro/portfolio3.jpg',
      description: '포트폴리오 설명 35',
      category: 'Arduino',
      layoutType: 'text',
    },
  ],
}

export default kiroContent
